### PR TITLE
Skip guice injector creation when possible

### PR DESCRIPTION
**Pull request by kokosing**

### CODE REVIEW

**Comment by kokosing** [comment]
I have hit some issues when testing Presto with tempto 167. Some of the tests (like `TestRoles`) were modifying query executor state that was causing other tests to fail.

**Comment by findepi** [comment]
> Some of the tests (like `TestRoles`) were modifying query executor state that was causing other tests to fail.

would https://github.com/prestosql/tempto/pull/15 help?

**Comment by kokosing** [comment]
I think #15 could help, but I would need to find all tests that are vulnerable to query executor state and fix them. I don't want to do this now.

**Comment by kokosing** [comment]
@sopel39 @findepi ping. This is ready to go.

**Review by sopel39 — APPROVED** [review]

**Pull request merged**
